#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: INFO
integration:
  operaton:
    url: http://operaton.url
  citizen:
    url: http://citizen.url
  templating:
    url: http://templating.url
    mottagningsbevis-template-identifier: egensotning-mottagningsbevis
  messaging:
    url: http://messaging.url
  eneo:
    space-id: 00000000-0000-0000-0000-000000000000
    assistants:
      brandskyddskontroll: 00000000-0000-0000-0000-000000000001
      egensotning: 00000000-0000-0000-0000-000000000002
    oauth2:
      token-url: http://token.url
      client-id: the-client-id
      client-secret: the-client-secret
    municipalities:
      2281:
        url: http://eneo.url
        api-key: the-api-key
scheduler:
  notification-cleanup:
    cron: '-'
    name: notification-cleanup
    shedlock-lock-at-most-for: PT5M
    maximum-execution-time: PT5M
  egensotning-expiry-reminder:
    cron: '-'
    name: egensotning-expiry-reminder
    shedlock-lock-at-most-for: PT5M
    maximum-execution-time: PT10M
    lead-time-days: 90
spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///junittest
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: update
  security:
    oauth2:
      client:
        provider:
          operaton:
            token-uri: http://token.url
          citizen:
            token-uri: http://token.url
          templating:
            token-uri: http://token.url
          messaging:
            token-uri: http://token.url
        registration:
          operaton:
            client-id: the-client-id
            client-secret: the-client-secret
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          templating:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
