#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: INFO
integration:
  operaton:
    url: http://localhost:${wiremock.server.port:}/api-operaton
  citizen:
    url: http://localhost:${wiremock.server.port:}/api/v3/citizen
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  security:
    oauth2:
      client:
        provider:
          operaton:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          citizen:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          operaton:
            client-id: the-client-id
            client-secret: the-client-secret
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
